### PR TITLE
Complete Linux Compatibility

### PR DESCRIPTION
**Pull request by calebkleveter**
- [x] Add GitHub CI workflow to always check Linux (Ubuntu Bionic) support
- [x] Compile on Linux
- [ ] All tests pass on Linux

Currently, the issue that we are running into right now is the `CoFutureAwaitTests.testAwait` test case is exiting with a signal code 6 and literally no other information.

### CODE REVIEW

**Comment by belozierov** [comment]
Wow! Thank you very much, it's awesome))
Could you please also add iOS besides macOS support?

**Comment by calebkleveter** [comment]
@belozierov Sure, I can look at that! In a best-case scenario, I just need to add the GitHub Action and it will just work. We'll see. 😄

**Comment by belozierov** [comment]
@calebkleveter Keep in mind there is the bug which causes `testHandlersCancel` fail in` CoFutureOperatorsTests`. It would be better to comment the test. I’ll fix it later.

**Comment by belozierov** [comment]
It looks like that is the reason why CI tests fail.

**Comment by belozierov** [comment]
Now it has Linux support)

**Pull request closed without merging**
